name: CI

on: 
  pull_request:
    branches: 
      - main

jobs:
  build:
    name: Linux build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Configure
      run: |
        mkdir ../build
        cd ../build
        cmake -DBUILD_GMOCK=OFF -DINSTALL_GTEST=ON -DCOMP_TESTS=ON -DCOMP_EXAMPLES=ON ../libcomp
    - name: Build debug
      run: |
        cmake -DBUILD_GMOCK=OFF -DINSTALL_GTEST=ON -DCOMP_TESTS=ON -DCOMP_EXAMPLES=ON ../libcomp
        cmake --build . --config Debug --target all
    - name: Run connect example
      run: |
        cd examples/connect
        ./connect
    - name: Run disconnect example
      run: |
        cd examples/disconnect
        ./disconnect
    - name: Run track_tracker example
      run: |
        cd examples/track_tracker
        ./track_tracker
    - name: Run track_shared_tracker example
      run: |
        cd examples/track_shared_tracker
        ./track_shared_tracker
    - name: Run unit tests
      run: |
        cd tests
        ./unittests

