name: CI

on: 
  pull_request:
    branches: 
      - main

jobs:
  build:
    name: Linux build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Configure
      run: |
        mkdir ../build
        cd ../build
        cmake -DBUILD_GMOCK=OFF -DINSTALL_GTEST=ON -DCOMP_TESTS=ON ../sywu
    - name: Build debug
      run: |
        cmake -DBUILD_GMOCK=OFF -DINSTALL_GTEST=ON -DCOMP_TESTS=ON ../sywu
        cmake --build . --config Debug --target all
    - name: Run unit tests
      run: |
        cd tests
        ./unittests

